In [90]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:96% !important; }</style>"))

In [3]:
import datetime

In [5]:
print("Started at : ", datetime.datetime.now())

Started at :  2023-11-03 18:18:28.464784


In [18]:
import requests
from zipfile import ZipFile

In [16]:
d = requests.get("https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip")

In [19]:
with open("data/getting_started.zip", "wb") as f:
    f.write(d.content)

In [21]:
with ZipFile("data/getting_started.zip", 'r') as z:
    z.extractall("data/")

In [22]:
import pandas as pd

In [24]:
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")

In [26]:
import numpy as np
import random
random.seed(42)
np.random.seed(42)

In [27]:
train_df.shape, test_df.shape

((7613, 5), (3263, 4))

In [28]:
train_df_shuffled = train_df.sample(frac=1, random_state=42)

In [29]:
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [30]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [91]:
train_df['target'].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [82]:
for _ in range(10):
    random_no = random.randint(0, len(train_df)-1)
    print("\033[0mLabel : ",f"\033[1m{train_df_shuffled.target[random_no]}")
    print(f"\033[0mText : " , f"\033[1m{train_df_shuffled.text[random_no]}")
    print("")

Label :  1
Text :  Oregon's biggest wildfire slows growth http://t.co/P0GoS5URXG via @katunews

Label :  0
Text :  #ActionMoviesTaughtUs things actually can explode with a loud bang...in space.

Label :  1
Text :  'Tube strike live: Latest travel updates as London engulfed in chaos' &lt;- genuine baffling Telegraph headline

Label :  1
Text :  'Drowning' - Acrylic 08.05.15 https://t.co/X17fUBQBGG

Label :  0
Text :  cPanel Crash Course http://t.co/bIRKbje23e #course http://t.co/buZWJmW49e

Label :  1
Text :  The cryptic words that guided pilots on the Hiroshima bombing mission http://t.co/FCe0K1Ihti

Label :  0
Text :  @TasteMyCupCakee lmfaooo  hell nawh ?? yo ass thought ??

Label :  1
Text :  @gilmanrocks7 wow. Where is this? For the rest of the summer I usually have to worry about forest fires. Calgary is about 8 hours away.

Label :  1
Text :  @Benjm1 @TourofUtah @B1Grego saw that pileup on TV keep racing even bleeding

Label :  0
Text :  I added a video to a @YouTube playlist http

 - `Diaster - 1`

 - `Not Real Diaster - 0`

## Data Spliting

In [83]:
from sklearn.model_selection import train_test_split

In [85]:
train_data , val_data , train_label , val_label = train_test_split \
                                                    (
                                                    train_df_shuffled['text'].to_numpy(),
                                                    train_df_shuffled['target'].to_numpy(),
                                                    test_size=0.1,
                                                    random_state=42
                                                    )

In [88]:
print(len(train_data), len(val_data), len(train_label), len(val_label))

6851 762 6851 762


In [92]:
train_data[:10], train_label[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

In [186]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [191]:
text_vectorizer = TextVectorization(
    max_tokens=None,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=None,
    output_mode='int',
    vocabulary=None)

In [193]:
text_vectorizer.get_vocabulary()

['', '[UNK]']

In [197]:
' '.join([str(len(_.split(" "))) for _ in train_data])

'7 6 20 12 7 17 5 13 25 15 19 11 20 22 9 24 19 6 4 12 8 6 17 17 7 18 19 26 21 10 27 14 5 7 11 7 15 6 11 23 8 17 17 17 3 20 9 9 4 8 19 17 23 20 8 13 19 8 17 8 12 9 25 15 20 8 7 11 12 18 19 10 22 18 11 21 9 16 2 15 25 11 12 20 19 14 16 4 21 9 17 14 11 20 15 12 21 26 12 20 15 15 22 14 11 10 13 11 9 22 22 16 15 5 20 10 15 19 20 10 17 15 12 3 9 3 8 13 8 18 3 15 14 10 22 11 15 21 22 18 8 12 5 18 9 14 8 17 7 18 18 15 7 8 15 28 7 6 11 16 21 11 21 16 22 18 22 7 22 15 19 21 2 21 13 4 23 16 16 18 22 18 22 14 15 18 2 23 11 9 19 24 22 2 9 14 19 14 20 12 11 18 22 19 15 23 20 23 7 7 15 9 13 24 8 17 14 18 17 12 19 11 19 18 14 17 9 10 12 8 14 12 3 20 23 24 18 17 23 28 26 21 24 8 17 10 19 23 11 20 21 19 24 17 12 17 9 16 24 22 18 17 13 24 7 12 18 15 19 11 16 18 11 20 22 24 16 11 17 12 11 2 10 19 19 16 12 18 24 8 7 17 14 20 11 12 15 12 23 5 19 15 16 11 18 19 16 27 19 9 22 11 10 20 19 12 15 13 31 4 23 16 24 16 17 9 7 10 8 6 6 9 13 8 14 20 8 22 11 9 13 11 7 12 15 11 20 3 11 14 12 10 20 12 20 11 17 8 11 5 10

In [202]:
int(np.ceil(sum(len(_.split(' ')) for _ in train_data ) / len(train_data)))

15

In [203]:
max_tokens = 15000
max_length = int(np.ceil(sum(len(_.split(' ')) for _ in train_data ) / len(train_data)))

In [204]:
text_vectorizer = TextVectorization(max_tokens=max_tokens,
                                    output_mode='int',
                                   output_sequence_length=max_length)

In [205]:
text_vectorizer.get_vocabulary()

['', '[UNK]']

In [206]:
text_vectorizer.adapt(train_data)

In [212]:
sample_data = "Earthquake & flood just hit in Indonesia"
text_vectorizer([sample_data])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 290,  232,   29,  244,    4, 3744,    0,    0,    0,    0,    0,
           0,    0,    0,    0]], dtype=int64)>

In [225]:
# Let's Visualize the data 
def show_rand_data(train_data, text_vectorizer):
    _ = np.random.choice(train_data)
    print(f"Text :  {_}\n")
    print((text_vectorizer([_])))
    

In [226]:
show_rand_data(train_data, text_vectorizer)

Text :  Italy: Three dead after landslide in the Italian Alps: http://t.co/42MawZb8T9 via @YouTube

tf.Tensor(
[[2419  564  115   43  374    4    2 1830 2564    1   49  114    0    0
     0]], shape=(1, 15), dtype=int64)


In [232]:
wordlist = [_ for _ in text_vectorizer.get_vocabulary()]

In [234]:
wordlist[:10], wordlist[-10:]

(['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'],
 ['httptcoe9d9lk5fdw',
  'httptcoe981dgskab',
  'httptcoe90j3vjolc',
  'httptcoe84ifmcczn',
  'httptcoe7ojhpdfg2',
  'httptcoe7fn5g5ruu',
  'httptcoe65v80fcus',
  'httptcoe61x9y65qd',
  'httptcoe5cns6ufpa',
  'httptcoe4ydbm4dx6'])

In [235]:
len(wordlist)

15000