In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#Tenosrflow Constant ; The Values can't be changed here
tensor_1 = tf.constant(7,shape=(4,5))
tensor_2 = tf.constant((1),dtype=np.uint16,shape=(2,4))

In [3]:
tensor_1, tensor_2
# for i in range(len(tensor_2.shape)): print(tensor_2[i])
# type(tensor_2)

(<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
 array([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])>,
 <tf.Tensor: shape=(2, 4), dtype=uint16, numpy=
 array([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=uint16)>)

## TensorFlow Variables

In [4]:
tensor_v1 = tf.Variable([5,6])

In [5]:
tensor_v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6])>